### ISSUE TITLE
Not working on react-native version "^0.49.3"

### ISSUE THREAD

**Issue by hajoeun** [hushicai/ReactNativeAndroidWebView#1]
I want to use your code.
But it does not working on version "^0.49.3".
Have you ever test on that version? 

![image](https://user-images.githubusercontent.com/8841586/31530947-c84e0b08-b01e-11e7-8db4-eda8d19d5034.png)

**Comment by hushicai** [comment]
`CustomWebView.android.js` is copied from `WebView.android.js`, so if you meet some problem like missing props, you should check that if the new version of `WebView.android.js`  has added some new props. if so, you can copied the new `WebView.android.js` to `CustomWebView.android.js`,and modified it for using `CustomWebViewManager`.
