### ISSUE TITLE
Update to work with RN 0.50.3 now that #15016 has landed?

### ISSUE THREAD

**Issue by dahjelle** [hushicai/ReactNativeAndroidWebView#2]
I see that has landed in the latest React Native. Any chance you have an updated example? (I haven't figured out how your code or the PR work yet…I'll report back later if I figure it out.)

**Comment by hushicai** [comment]
@dahjelle You can override `src/CustomWebView.android.js` with the new feature facebook/react-native#15016

**Comment by dahjelle** [comment]
In case anyone else is curious, here's what I came up with using the latest React Native: https://github.com/dahjelle/react-native-android-webview-file-image-upload
